---
 
- name: 'Include all variables'
  include_vars:
    dir: /opt/roles/webapp/vars

- name: 'Install git on servers'
  yum:
    name: git
    state: installed
    update_cache: yes

- name: 'Path for git initialization and html project'
  file:
    path: "/{{ webapp_installation_path }}/www/html"
    state: directory
   
