---
 
- name: 'Include all variables'
  include_vars:
    dir: /opt/roles/webapp/vars

- name: 'Install git on servers'
  yum:
    name: git
    state: installed
    update_cache: yes

- name: 'Create ssh key for git repo auth'
  command: ssh-keygen -t rsa -b 4096 -f ~/.ssh/webapp_rsa
  args:
    creates: ~/.ssh/webapp_rsa.pub

- name: 'Create ssh config file'
  copy:
    src: /opt/roles/git/files/config
    dest: ~/.ssh/config
    owner: root
    group: root
    mode: '755'

- name: Clone a private repository into /opt.
  git:
    repo: "{{ git_repo_url }}"
    version: main
    dest: /opt/webapp
    accept_hostkey: yes
  become: no


#- name: 'Clone webapp github repository'
#  command: git clone {{ git_repo_url }}
#  args:
#    chdir: /opt/



#- name: 'Initialize git'
#  command: git init
#  args:
#    chdir: "{{ webapp_installation_path }}"
