---
 
- name: 'Include all variables'
  include_vars:
    dir: /opt/roles/webapp/vars

- name: 'Install git on servers'
  yum:
    name: git
    state: installed
    update_cache: yes

- name: 'Create ssh key for git repo auth'
  command: "ssh-keygen -t rsa -b 4096 -f ~/.ssh/{{ ssh_key_name }} -N ''"
  args:
    creates: "~/.ssh/{{ ssh_key_name }}"

- name: 'Create ssh config file'
  copy:
    src: config
    dest: ~/.ssh/config
    owner: root
    group: root
    mode: '755'

- name: Clone a private repository into /opt.
  git:
    repo: "{{ git_repo_url }}"
    version: main
    dest: "{{ webapp_installation_path }}" 
    accept_hostkey: yes
  become: no

- name: Git fetch 
  command: git fetch
  args:
    chdir: "{{ webapp_installation_path }}"

- name: Git pull
  command: git pull
  args:
    chdir: "{{ webapp_installation_path }}"

