---
- name: 'Download httpd rpm package'
  get_url:
    url: http://ftp.itu.edu.tr/Mirror/CentOS/7/updates/x86_64/Packages/httpd-2.4.6-97.el7.centos.x86_64.rpm
    dest: /home/

- name: 'Install httpd service'
  yum:
    name: /home/httpd-2.4.6-97.el7.centos.x86_64.rpm
    state: installed

- name: 'Modify httpd configuration'
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf 

- name: 'Transfer necessary webapp files'
  copy:
    src: /root/http_service/files/index.html
    dest: "{{ webapp_installation_path }}/www/html/index.html"
    owner: root
    group: root
    mode: '755'
  notify:
    - Restart httpd

- name: 'Start httpd service'
  systemd:
    name: httpd
    state: started
    enabled: yes
    masked: no
