---
- name: 'Download httpd rpm package'
  get_url:
    url: "{{ rpm_url }}"
    dest: /home/

- name: 'Install httpd service'
  yum:
    name: "/home/{{ rpm_name }}"
    state: installed

- name: 'Modify httpd configuration'
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf 

- name: 'Start httpd service'
  systemd:
    name: httpd
    state: started
    enabled: yes
    masked: no
